name: master

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  master-build-and-maybe-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: npm ci
      - run: npm ci
        working-directory: functions
      - run: npm run build
      - run: npm run test
      - name: Deploy to Firebase
        if: ${{ github.event_name == 'push' }}
        uses: w9jds/firebase-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: deploy --debug
